import type { Game, User } from '@/types'

// TODO(real-api): Replace this file with API calls to /api/games and /api/users
// All functions here are designed to mirror real REST shapes for easy swap.

export const MOCK_GAMES: Game[] = [
  {
    id: '1',
    title: 'Elden Ring',
    genre: 'RPG',
    subGenres: ['Adventure'],
    rating: 9.6,
    playTime: '60-100 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'An action RPG set in the Lands Between, featuring vast open-world exploration, brutal combat, and a story co-created by George R.R. Martin.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7u3f.webp',
      'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7u3g.webp',
    ],
    matchPercentage: 96,
    releaseDate: '2022-02-25',
    developer: 'FromSoftware',
    tags: ['Open World', 'Souls-like', 'Fantasy', 'Difficult'],
  },
  {
    id: '2',
    title: 'Cyberpunk 2077',
    genre: 'RPG',
    subGenres: ['Adventure'],
    rating: 8.8,
    playTime: '50-80 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'An open-world action RPG set in the dark future of Night City — a megalopolis obsessed with power, glamour, and body modification.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4hp0.webp',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6rox.webp',
    ],
    matchPercentage: 89,
    releaseDate: '2020-12-10',
    developer: 'CD Projekt Red',
    tags: ['Open World', 'Cyberpunk', 'Story-Rich', 'FPS'],
  },
  {
    id: '3',
    title: 'Valorant',
    genre: 'FPS',
    rating: 8.5,
    playTime: '∞ Competitive',
    platform: ['PC'],
    description:
      'A 5v5 tactical shooter where precise gunplay meets unique agent abilities. Every round is a battle of strategy, reflexes, and teamwork.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2mvt.webp',
    screenshots: [],
    matchPercentage: 92,
    releaseDate: '2020-06-02',
    developer: 'Riot Games',
    tags: ['Tactical', 'Competitive', 'Team-based', 'Free-to-play'],
  },
  {
    id: '4',
    title: 'League of Legends',
    genre: 'MOBA',
    rating: 8.2,
    playTime: '∞ Competitive',
    platform: ['PC'],
    description:
      'The world\'s most popular MOBA. Choose from 160+ champions and battle to destroy the enemy Nexus in this legendary team strategy game.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co49wj.webp',
    screenshots: [],
    matchPercentage: 78,
    releaseDate: '2009-10-27',
    developer: 'Riot Games',
    tags: ['MOBA', 'Competitive', 'Free-to-play', 'Team'],
  },
  {
    id: '5',
    title: 'GTA V',
    genre: 'Adventure',
    rating: 9.0,
    playTime: '30-100 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'Three unique criminals team up in a massive open-world crime saga. GTA Online keeps the world alive with constant new content.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/cob5.webp',
    screenshots: [],
    matchPercentage: 85,
    releaseDate: '2013-09-17',
    developer: 'Rockstar Games',
    tags: ['Open World', 'Crime', 'Online', 'Story-Rich'],
  },
  {
    id: '6',
    title: 'Red Dead Redemption 2',
    genre: 'Adventure',
    subGenres: ['RPG'],
    rating: 9.7,
    playTime: '60-120 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'An epic tale of life in America\'s unforgiving heartland. Experience one of the most immersive open worlds ever created.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/coew2z.webp',
    screenshots: [],
    matchPercentage: 94,
    releaseDate: '2018-10-26',
    developer: 'Rockstar Games',
    tags: ['Open World', 'Western', 'Story-Rich', 'Cinematic'],
  },
  {
    id: '7',
    title: "Baldur's Gate 3",
    genre: 'RPG',
    subGenres: ['Strategy'],
    rating: 9.8,
    playTime: '100-200 hours',
    platform: ['PC', 'PlayStation'],
    description:
      'A legendary RPG that redefines the genre. Every choice matters in this massive D&D adventure filled with branching stories.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6ly7.webp',
    screenshots: [],
    matchPercentage: 91,
    releaseDate: '2023-08-03',
    developer: 'Larian Studios',
    tags: ['Turn-based', 'D&D', 'Multiplayer', 'Story-Rich'],
  },
  {
    id: '8',
    title: 'Minecraft',
    genre: 'Survival',
    subGenres: ['Adventure'],
    rating: 9.3,
    playTime: '∞ Sandbox',
    platform: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
    description:
      'The best-selling game of all time. Build anything, survive everything, and explore infinite procedurally generated worlds.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.webp',
    screenshots: [],
    matchPercentage: 72,
    releaseDate: '2011-11-18',
    developer: 'Mojang',
    tags: ['Sandbox', 'Creative', 'Survival', 'Family'],
  },
  {
    id: '9',
    title: 'Apex Legends',
    genre: 'FPS',
    subGenres: ['Survival'],
    rating: 8.7,
    playTime: '∞ Battle Royale',
    platform: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
    description:
      'A free-to-play hero battle royale where legendary competitors fight for glory and fortune in a futuristic frontier world.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1gqu.webp',
    screenshots: [],
    matchPercentage: 88,
    releaseDate: '2019-02-04',
    developer: 'Respawn Entertainment',
    tags: ['Battle Royale', 'Hero Shooter', 'Free-to-play', 'Fast-paced'],
  },
  {
    id: '10',
    title: 'The Witcher 3',
    genre: 'RPG',
    subGenres: ['Adventure'],
    rating: 9.8,
    playTime: '80-200 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'Play as Geralt of Rivia, a professional monster hunter in a morally complex fantasy world. Winner of 800+ Game of the Year awards.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.webp',
    screenshots: [],
    matchPercentage: 97,
    releaseDate: '2015-05-19',
    developer: 'CD Projekt Red',
    tags: ['Open World', 'Fantasy', 'Story-Rich', 'Mature'],
  },
  {
    id: '11',
    title: 'Fortnite',
    genre: 'FPS',
    subGenres: ['Survival'],
    rating: 7.8,
    playTime: '∞ Battle Royale',
    platform: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
    description:
      'Drop into the most popular battle royale game in the world. Build, fight, and survive to be the last one standing.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3wk8.webp',
    screenshots: [],
    matchPercentage: 75,
    releaseDate: '2017-07-25',
    developer: 'Epic Games',
    tags: ['Battle Royale', 'Building', 'Free-to-play', 'Casual'],
  },
  {
    id: '12',
    title: 'God of War',
    genre: 'Adventure',
    subGenres: ['RPG'],
    rating: 9.5,
    playTime: '20-40 hours',
    platform: ['PC', 'PlayStation'],
    description:
      'Father and son journey through Norse mythology in this deeply emotional action-adventure masterpiece.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.webp',
    screenshots: [],
    matchPercentage: 93,
    releaseDate: '2018-04-20',
    developer: 'Santa Monica Studio',
    tags: ['Norse Mythology', 'Action', 'Story-Rich', 'Combat'],
  },
  {
    id: '13',
    title: 'Overwatch 2',
    genre: 'FPS',
    subGenres: ['MOBA'],
    rating: 7.5,
    playTime: '∞ Team-based',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'A team-based hero shooter where you play as powerful heroes with unique abilities in dynamic 5v5 battles.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.webp',
    screenshots: [],
    matchPercentage: 80,
    releaseDate: '2022-10-04',
    developer: 'Blizzard Entertainment',
    tags: ['Hero Shooter', 'Team-based', 'Free-to-play', 'Competitive'],
  },
  {
    id: '14',
    title: 'Starfield',
    genre: 'RPG',
    subGenres: ['Adventure'],
    rating: 7.9,
    playTime: '40-100 hours',
    platform: ['PC', 'Xbox'],
    description:
      'The first new universe from Bethesda in 25 years. Explore over 1,000 planets in humanity\'s golden age of space exploration.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6dn2.webp',
    screenshots: [],
    matchPercentage: 82,
    releaseDate: '2023-09-06',
    developer: 'Bethesda Game Studios',
    tags: ['Space', 'Open World', 'Sci-Fi', 'Exploration'],
  },
  {
    id: '15',
    title: 'FIFA 24',
    genre: 'Racing',
    rating: 7.2,
    playTime: '∞ Sports',
    platform: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
    description:
      'The world\'s most popular football game featuring HyperMotion technology, Ultimate Team, and Career Mode.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co75np.webp',
    screenshots: [],
    matchPercentage: 65,
    releaseDate: '2023-09-29',
    developer: 'EA Sports',
    tags: ['Sports', 'Football', 'Online', 'Competitive'],
  },
  {
    id: '16',
    title: 'Dota 2',
    genre: 'MOBA',
    rating: 8.6,
    playTime: '∞ Competitive',
    platform: ['PC'],
    description:
      'The deepest MOBA ever made. 120+ heroes, infinite strategies, and a skill ceiling that never stops growing.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r9m.webp',
    screenshots: [],
    matchPercentage: 77,
    releaseDate: '2013-07-09',
    developer: 'Valve',
    tags: ['MOBA', 'Competitive', 'Free-to-play', 'Strategy'],
  },
  {
    id: '17',
    title: 'Hollow Knight',
    genre: 'Adventure',
    subGenres: ['RPG'],
    rating: 9.3,
    playTime: '25-50 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'Forge your own path in a vast underground kingdom of insects and heroes. A gorgeous 2D action-adventure.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.webp',
    screenshots: [],
    matchPercentage: 86,
    releaseDate: '2017-02-24',
    developer: 'Team Cherry',
    tags: ['Metroidvania', 'Difficult', 'Beautiful', 'Indie'],
  },
  {
    id: '18',
    title: 'Hades',
    genre: 'RPG',
    subGenres: ['Adventure'],
    rating: 9.2,
    playTime: '20-80 hours',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'Defy the god of the Underworld as Zagreus in this rogue-like dungeon crawler with stunning art and divine storytelling.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2yw6.webp',
    screenshots: [],
    matchPercentage: 90,
    releaseDate: '2020-09-17',
    developer: 'Supergiant Games',
    tags: ['Roguelike', 'Greek Mythology', 'Action', 'Indie'],
  },
  {
    id: '19',
    title: 'Age of Empires IV',
    genre: 'Strategy',
    rating: 8.4,
    playTime: '∞ Strategy',
    platform: ['PC'],
    description:
      'Lead one of eight civilizations across history in this landmark real-time strategy game. Build, conquer, and expand your empire.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3hyn.webp',
    screenshots: [],
    matchPercentage: 73,
    releaseDate: '2021-10-28',
    developer: 'Relic Entertainment',
    tags: ['RTS', 'Historical', 'Multiplayer', 'Complex'],
  },
  {
    id: '20',
    title: 'Horizon Zero Dawn',
    genre: 'Adventure',
    subGenres: ['RPG'],
    rating: 9.0,
    playTime: '30-60 hours',
    platform: ['PC', 'PlayStation'],
    description:
      'Hunt machines as Aloy in a breathtaking post-apocalyptic world where robot dinosaurs roam and ancient mysteries await.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rh5.webp',
    screenshots: [],
    matchPercentage: 88,
    releaseDate: '2017-02-28',
    developer: 'Guerrilla Games',
    tags: ['Open World', 'Sci-Fi', 'Hunting', 'Story-Rich'],
  },
  {
    id: '21',
    title: 'Rocket League',
    genre: 'Racing',
    rating: 8.8,
    playTime: '∞ Competitive',
    platform: ['PC', 'PlayStation', 'Xbox'],
    description:
      'Soccer meets racing in this physics-based vehicular soccer phenomenon. Easy to learn, impossible to master.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ycl.webp',
    screenshots: [],
    matchPercentage: 84,
    releaseDate: '2015-07-07',
    developer: 'Psyonix',
    tags: ['Sports', 'Competitive', 'Casual', 'Free-to-play'],
  },
  {
    id: '22',
    title: 'Among Us',
    genre: 'Strategy',
    subGenres: ['Survival'],
    rating: 7.9,
    playTime: '∞ Party',
    platform: ['PC', 'Mobile'],
    description:
      'Work together to complete tasks aboard a spaceship — but beware the impostors lurking among you. A social deduction classic.',
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co272q.webp',
    screenshots: [],
    matchPercentage: 70,
    releaseDate: '2018-11-16',
    developer: 'InnerSloth',
    tags: ['Social', 'Party', 'Deduction', 'Free-to-play'],
  },
]

export const MOCK_USER: User = {
  id: 'mock-user-1',
  username: 'GameMaster',
  email: 'player@smartgamematcher.io',
  preferences: {
    genres: [],
    playStyle: null,
    dailyPlayTime: null,
    mood: null,
    platform: null,
  },
  createdAt: new Date().toISOString(),
}
